// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zlYVbIncRlsF5zrLryz-4sZ0Mx3_hXM',
    appId:
        '1:926130951089:web:YOUR_WEB_APP_ID', // ستحتاج إلى إضافة web app في Firebase
    messagingSenderId: '926130951089',
    projectId: 'bilink-9381c',
    authDomain: 'bilink-9381c.firebaseapp.com',
    storageBucket: 'bilink-9381c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6zlYVbIncRlsF5zrLryz-4sZ0Mx3_hXM',
    appId: '1:926130951089:android:eeae9b3f562c78f4ea2390',
    messagingSenderId: '926130951089',
    projectId: 'bilink-9381c',
    storageBucket: 'bilink-9381c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // ستحتاج إلى إضافة iOS app في Firebase
    appId: '1:926130951089:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '926130951089',
    projectId: 'bilink-9381c',
    storageBucket: 'bilink-9381c.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.example.bilink',
  );
}
